from __future__ import annotations

from bank_env.server.mock_db import CHEQUE_DIR, EXTERNAL_CHEQUE_DIR


def get_cases() -> list[dict]:
    return [
        {
            "cheque_id": "EASY-001",
            "difficulty": "easy",
            "cheque_image_path": str(EXTERNAL_CHEQUE_DIR / "cheque1.jpg"),
            "signature_image_path": str(EXTERNAL_CHEQUE_DIR / "cheque1_signature.jpg"),
            "ground_truth": {
                "final_decision": "APPROVED",
                "issues": {
                    "data_valid": True,
                    "signature_valid": True,
                    "account_valid": True,
                    "balance_ok": True,
                    "transfer_success": True,
                },
            },
            "record": {
                "date": "20/01/2015",
                "amount_words": "Two lakh ten thousand and five hundred",
                "amount_digits": 210500.0,
                "payee_name": "Amita Kadam",
                "bank_name": "Axis Bank",
                "micr_code": "426160031",
                "cheque_number": "309155",
                "account_number": "911010049001545",
                "drawer_name": "Rajarshi Pal",
                "ifsc": "UTIB0000426",
                "bank_branch": "Mehdipatnam",
                "payee_bank": "Axis Bank",
            },
            "extracted_data": {
                "date": "20/01/2015",
                "amount_words": "Two lakh ten thousand and five hundred",
                "amount_digits": 210500.0,
                "payee_name": "Amita Kadam",
                "bank_name": "Axis Bank",
                "micr_code": "426160031",
                "cheque_number": "309155",
                "account_number": "911010049001545",
                "drawer_name": "Rajarshi Pal",
                "ifsc": "UTIB0000426",
                "bank_branch": "Mehdipatnam",
                "payee_bank": "Axis Bank",
            },
        },
        {
            "cheque_id": "EASY-002",
            "difficulty": "easy",
            "cheque_image_path": str(CHEQUE_DIR / "cheque1.png"),
            "signature_image_path": str(CHEQUE_DIR / "cheque1_signature.png"),
            "ground_truth": {
                "final_decision": "APPROVED",
                "issues": {"data_valid": True, "signature_valid": True, "account_valid": True, "balance_ok": True, "transfer_success": True},
            },
            "record": {
                "date": "02/04/2026",
                "amount_words": "Two thousand four hundred",
                "amount_digits": 2400.0,
                "payee_name": "Vendor A",
                "bank_name": "Axis Bank",
                "micr_code": "426160001",
                "cheque_number": "E24001",
                "account_number": "ACC001",
                "drawer_name": "Harman",
                "ifsc": "UTIB0000426",
                "bank_branch": "Hyderabad",
                "payee_bank": "Axis Bank",
            },
            "extracted_data": {
                "date": "02/04/2026",
                "amount_words": "Two thousand four hundred",
                "amount_digits": 2400.0,
                "payee_name": "Vendor A",
                "bank_name": "Axis Bank",
                "micr_code": "426160001",
                "cheque_number": "E24001",
                "account_number": "ACC001",
                "drawer_name": "Harman",
                "ifsc": "UTIB0000426",
                "bank_branch": "Hyderabad",
                "payee_bank": "Axis Bank",
            },
        },
        {
            "cheque_id": "EASY-003",
            "difficulty": "easy",
            "cheque_image_path": str(CHEQUE_DIR / "cheque3.png"),
            "signature_image_path": str(CHEQUE_DIR / "cheque3_signature.png"),
            "ground_truth": {
                "final_decision": "APPROVED",
                "issues": {"data_valid": True, "signature_valid": True, "account_valid": True, "balance_ok": True, "transfer_success": True},
            },
            "record": {
                "date": "02/04/2026",
                "amount_words": "One thousand eight hundred",
                "amount_digits": 1800.0,
                "payee_name": "Vendor C",
                "bank_name": "Axis Bank",
                "micr_code": "426160001",
                "cheque_number": "E18003",
                "account_number": "ACC001",
                "drawer_name": "Harman",
                "ifsc": "UTIB0000426",
                "bank_branch": "Hyderabad",
                "payee_bank": "Axis Bank",
            },
            "extracted_data": {
                "date": "02/04/2026",
                "amount_words": "One thousand eight hundred",
                "amount_digits": 1800.0,
                "payee_name": "Vendor C",
                "bank_name": "Axis Bank",
                "micr_code": "426160001",
                "cheque_number": "E18003",
                "account_number": "ACC001",
                "drawer_name": "Harman",
                "ifsc": "UTIB0000426",
                "bank_branch": "Hyderabad",
                "payee_bank": "Axis Bank",
            },
        },
    ]
