from __future__ import annotations

from server.mock_db import EXTERNAL_CHEQUE_DIR


def get_cases() -> list[dict]:
    return [
        {
            "cheque_id": "HARD-001",
            "difficulty": "hard",
            "cheque_image_path": str(EXTERNAL_CHEQUE_DIR / "cheque3.jpg"),
            "signature_image_path": str(EXTERNAL_CHEQUE_DIR / "cheque3_signature.jpg"),
            "ground_truth": {
                "final_decision": "REJECTED",
                "issues": {"data_valid": False, "signature_valid": False, "account_valid": True, "balance_ok": False, "transfer_success": False},
            },
            "record": {
                "date": "20/12/2015",
                "amount_words": "Four crore twenty lakhs",
                "amount_digits": 42000000.0,
                "payee_name": "Chahat Thawa",
                "bank_name": "Axis Bank",
                "micr_code": "426160031",
                "cheque_number": "309158",
                "account_number": "911010049001545",
                "drawer_name": "Rajarshi Pal",
                "ifsc": "UTIB0000426",
                "bank_branch": "Mehdipatnam",
                "payee_bank": "ICICI Bank",
            },
            "extracted_data": {
                "date": "20/12/2015",
                "amount_words": "Four crore twenty lakhs",
                "amount_digits": 42000000.0,
                "payee_name": "Chahat Thawa",
                "bank_name": "Axis Bank",
                "micr_code": "426160031",
                "cheque_number": "309158X",
                "account_number": "911010049001545",
                "drawer_name": "Rajarshi Pal",
                "ifsc": "UTIB0000426",
                "bank_branch": "Mehdipatnam",
                "payee_bank": "ICICI Bank",
            },
        },
        {
            "cheque_id": "HARD-002",
            "difficulty": "hard",
            "cheque_image_path": str(EXTERNAL_CHEQUE_DIR / "cheque3.jpg"),
            "signature_image_path": str(EXTERNAL_CHEQUE_DIR / "cheque2_signature.jpg"),
            "ground_truth": {
                "final_decision": "REJECTED",
                "issues": {"data_valid": True, "signature_valid": False, "account_valid": True, "balance_ok": False, "transfer_success": False},
            },
            "record": {
                "date": "20/12/2015",
                "amount_words": "Four crore twenty lakhs",
                "amount_digits": 42000000.0,
                "payee_name": "Chahat Thawa",
                "bank_name": "Axis Bank",
                "micr_code": "426160031",
                "cheque_number": "309158",
                "account_number": "911010049001545",
                "drawer_name": "Rajarshi Pal",
                "ifsc": "UTIB0000426",
                "bank_branch": "Mehdipatnam",
                "payee_bank": "ICICI Bank",
            },
            "extracted_data": {
                "date": "20/12/2015",
                "amount_words": "Four crore twenty lakhs",
                "amount_digits": 42000000.0,
                "payee_name": "Chahat Thawa",
                "bank_name": "Axis Bank",
                "micr_code": "426160031",
                "cheque_number": "309158",
                "account_number": "911010049001545",
                "drawer_name": "Rajarshi Pal",
                "ifsc": "UTIB0000426",
                "bank_branch": "Mehdipatnam",
                "payee_bank": "ICICI Bank",
            },
        },
        {
            "cheque_id": "HARD-003",
            "difficulty": "hard",
            "cheque_image_path": str(EXTERNAL_CHEQUE_DIR / "cheque2.jpg"),
            "signature_image_path": str(EXTERNAL_CHEQUE_DIR / "cheque3_signature.jpg"),
            "ground_truth": {
                "final_decision": "REJECTED",
                "issues": {"data_valid": False, "signature_valid": False, "account_valid": True, "balance_ok": True, "transfer_success": False},
            },
            "record": {
                "date": "07/05/2016",
                "amount_words": "One lakh twenty five thousand",
                "amount_digits": 125000.0,
                "payee_name": "Sunil Kumar",
                "bank_name": "Axis Bank",
                "micr_code": "426160031",
                "cheque_number": "309157",
                "account_number": "911010049001545",
                "drawer_name": "Rajarshi Pal",
                "ifsc": "UTIB0000426",
                "bank_branch": "Mehdipatnam",
                "payee_bank": "HDFC Bank",
            },
            "extracted_data": {
                "date": "07/05/2016",
                "amount_words": "One lakh twenty thousand",
                "amount_digits": 125000.0,
                "payee_name": "Sunil Kumaar",
                "bank_name": "Axis Bank",
                "micr_code": "426160031",
                "cheque_number": "309157",
                "account_number": "911010049001545",
                "drawer_name": "Rajarshi Pal",
                "ifsc": "UTIB0000426",
                "bank_branch": "Mehdipatnam",
                "payee_bank": "HDFC Bank",
            },
        },
    ]
