from __future__ import annotations

from bank_env.server.mock_db import CHEQUE_DIR, EXTERNAL_CHEQUE_DIR


def get_cases() -> list[dict]:
    return [
        {
            "cheque_id": "MED-001",
            "difficulty": "medium",
            "cheque_image_path": str(EXTERNAL_CHEQUE_DIR / "cheque2.jpg"),
            "signature_image_path": str(EXTERNAL_CHEQUE_DIR / "cheque2_signature.jpg"),
            "ground_truth": {
                "final_decision": "REJECTED",
                "issues": {"data_valid": True, "signature_valid": False, "account_valid": True, "balance_ok": True, "transfer_success": False},
            },
            "record": {
                "date": "07/05/2016",
                "amount_words": "One lakh twenty five thousand",
                "amount_digits": 125000.0,
                "payee_name": "Sunil Kumar",
                "bank_name": "Axis Bank",
                "micr_code": "426160031",
                "cheque_number": "309157",
                "account_number": "911010049001545",
                "drawer_name": "Rajarshi Pal",
                "ifsc": "UTIB0000426",
                "bank_branch": "Mehdipatnam",
                "payee_bank": "HDFC Bank",
            },
            "extracted_data": {
                "date": "07/05/2016",
                "amount_words": "One lakh twenty five thousand",
                "amount_digits": 125000.0,
                "payee_name": "Sunil Kumar",
                "bank_name": "Axis Bank",
                "micr_code": "426160031",
                "cheque_number": "309157",
                "account_number": "911010049001545",
                "drawer_name": "Rajarshi Pal",
                "ifsc": "UTIB0000426",
                "bank_branch": "Mehdipatnam",
                "payee_bank": "HDFC Bank",
            },
        },
        {
            "cheque_id": "MED-002",
            "difficulty": "medium",
            "cheque_image_path": str(CHEQUE_DIR / "cheque2.png"),
            "signature_image_path": str(CHEQUE_DIR / "cheque2_signature.png"),
            "ground_truth": {
                "final_decision": "REJECTED",
                "issues": {"data_valid": True, "signature_valid": False, "account_valid": True, "balance_ok": False, "transfer_success": False},
            },
            "record": {
                "date": "02/04/2026",
                "amount_words": "Six thousand two hundred",
                "amount_digits": 6200.0,
                "payee_name": "Vendor B",
                "bank_name": "Axis Bank",
                "micr_code": "426160002",
                "cheque_number": "M62002",
                "account_number": "ACC002",
                "drawer_name": "Rahul",
                "ifsc": "UTIB0000426",
                "bank_branch": "Hyderabad",
                "payee_bank": "ICICI Bank",
            },
            "extracted_data": {
                "date": "02/04/2026",
                "amount_words": "Six thousand two hundred",
                "amount_digits": 6200.0,
                "payee_name": "Vendor B",
                "bank_name": "Axis Bank",
                "micr_code": "426160002",
                "cheque_number": "M62002",
                "account_number": "ACC002",
                "drawer_name": "Rahul",
                "ifsc": "UTIB0000426",
                "bank_branch": "Hyderabad",
                "payee_bank": "ICICI Bank",
            },
        },
        {
            "cheque_id": "MED-003",
            "difficulty": "medium",
            "cheque_image_path": str(EXTERNAL_CHEQUE_DIR / "cheque1.jpg"),
            "signature_image_path": str(EXTERNAL_CHEQUE_DIR / "cheque2_signature.jpg"),
            "ground_truth": {
                "final_decision": "REJECTED",
                "issues": {"data_valid": True, "signature_valid": False, "account_valid": True, "balance_ok": True, "transfer_success": False},
            },
            "record": {
                "date": "20/01/2015",
                "amount_words": "Two lakh ten thousand and five hundred",
                "amount_digits": 210500.0,
                "payee_name": "Amita Kadam",
                "bank_name": "Axis Bank",
                "micr_code": "426160031",
                "cheque_number": "309155",
                "account_number": "911010049001545",
                "drawer_name": "Rajarshi Pal",
                "ifsc": "UTIB0000426",
                "bank_branch": "Mehdipatnam",
                "payee_bank": "ICICI Bank",
            },
            "extracted_data": {
                "date": "20/01/2015",
                "amount_words": "Two lakh ten thousand and five hundred",
                "amount_digits": 210500.0,
                "payee_name": "Amita Kadam",
                "bank_name": "Axis Bank",
                "micr_code": "426160031",
                "cheque_number": "309155",
                "account_number": "911010049001545",
                "drawer_name": "Rajarshi Pal",
                "ifsc": "UTIB0000426",
                "bank_branch": "Mehdipatnam",
                "payee_bank": "ICICI Bank",
            },
        },
    ]
